### ISSUE TITLE
To-Do list associated with streamlining code and improving quality

### ISSUE THREAD

**Issue by MoAly98** [MoAly98/Pythium#36]
The following is a to-do list of work that need be done for the pre-processing and histogramming codes to interface nicely and provide a consistent UX:

For **sklimming**:
- [ ] Sklimming should replace the `Branch` objects with `Variable` or `Observable`. 
- [ ] The idea of `Functor` sub-class called `Builder` for a `Variable` is much neater than the `new_branches` dictionary. 
- [ ] Remove the `arg_types` argument for `Variable`/`Branch` objects and replace with an optional `list_str_arg` where the default assumption when a `str` is provided in argument becomes that it is a another `Branch`
- [ ] Sklimming back-end is too messy -- especially the organisation of different type of branches (new, tmp, on, off) 
- [ ] Dask distribution for the reading in the backend in a similar way to the histogramming code. 
- [ ] Consistent way of outputting yields using a given branch
- [ ] Config to use a schema in a similar way to histogramming
- [ ] `reader` code should be a processor code 
- [ ] Argparser to select `branches` and `samples` in stirring script
- [ ]  Look into a `coffea` backend

For **histogramming**:
- [ ] Provide an easy way for user to change sample settings -- does user really need anythig other than to set regex (i.e `tag` and specify if a sample `isdata`)? 
- [ ] The `input_paths` finder in `InputManager` should be able to handle user provided methods of finding paths, possibly via a decorator in the config? This is for users who have NTuples that they want to Histogram without running through pre-prcoessing 
- [ ] Data rendering before passing `awkward` arrays to `boost_histograms`. This probably means handling masked awkward arrays, since it seems like `boost_histograms` do not deal well with `None` in the `awkward`/`numpy` arrays (they get dumped in the underflow) [boost-histogram issue](https://github.com/scikit-hep/boost-histogram/discussions/714)

For both **sklimming** and **histogramming**:
- [ ] Remote distribution of jobs with `dask`(e.g. `HTCondotCluster`)
- [ ] Can Functor fromStr as it is parse slicing syntax?
- [ ] Test functions for all features

**Comment by MoAly98** [comment]
Mentioning the relevant pull request above which these changes are needed: #35
